package moe.ouom.neriplayer.architecture

import java.io.File
import org.junit.Assert.assertTrue
import org.junit.Test

class OwnedMainSourceLineBudgetTest {
    @Test
    fun `completed owned source sections stay below 2000 physical lines`() {
        val projectRoot = LocalManagementLineBudget.findProjectRoot(
            File(System.getProperty("user.dir") ?: ".")
        )
        listOf(
            "modules/data/repository/src/main/java/moe/ouom/neriplayer/data/settings/AutoSettingsSchema.kt",
            "modules/data/repository/src/main/java/moe/ouom/neriplayer/data/settings/playback/PlaybackSettingsSection.kt",
            "modules/api/bilibili/src/main/java/moe/ouom/neriplayer/api/bilibili/client/BiliClient.kt",
            "modules/api/bilibili/src/main/java/moe/ouom/neriplayer/api/bilibili/comment/BiliCommentApi.kt",
            "modules/api/bilibili/src/main/java/moe/ouom/neriplayer/api/bilibili/auth/BiliCookieSession.kt",
            "modules/api/bilibili/src/main/java/moe/ouom/neriplayer/api/bilibili/http/BiliRequestSupport.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/home/HomeScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/home/HomeContinueSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryPreflight.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/navigation/SettingsNavigationSearch.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsThemeControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingQueueSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricSettingsSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingSharedComponents.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupBackupRestoreStep.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreSearchResultRows.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreBrowseContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreGlassPillSurface.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/MainTabNavigationMotion.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/playback/SettingsPlaybackControlLayout.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsPersonalizationContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingPlaybackControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingSecondaryActions.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/artwork/PlaybackArtworkOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/artwork/PlaybackArtworkPolicies.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/artwork/PlaybackArtworkSources.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/artwork/PlaybackCoverSourceResolver.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/notification/PlaybackNotificationWidgetPresentation.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/presentation/PlaybackServiceMetadataPresentation.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/usb/UsbExclusiveServiceKeepAliveOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/usb/AndroidUsbExclusiveKeepAlivePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/usb/UsbExclusiveMediaSessionVolumeRouter.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/usb/AndroidUsbExclusiveVolumeRoutingPort.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/challenge/YouTubeStreamingCipherResolution.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/protocol/YouTubePlayerRequestComposer.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/AudioPlayerService.kt",
            "modules/core/player-policy/src/main/java/moe/ouom/neriplayer/core/player/policy/service/PlaybackServiceTaskRemovalPolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/presentation/PlaybackServicePresentationOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/presentation/PlaybackServicePresentationSource.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/service/presentation/AndroidPlaybackServicePresentationPort.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/protocol/YouTubePlayerResponseParsers.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveAudioSink.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusivePcmFormatPolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusivePcmWriter.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveSinkVolumeOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/AndroidUsbExclusiveSinkVolumePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveTransportStartPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCover.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverTopBar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingTrackIdentity.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverActionToolbar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverControlsPlacement.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverLyrics.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/client/YouTubeMusicClient.kt",
            "modules/data/model/src/main/java/moe/ouom/neriplayer/data/model/youtube/music/YouTubeMusicContentModels.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/parser/YouTubeMusicResponseParser.kt",
            "modules/data/youtube/src/main/java/moe/ouom/neriplayer/data/youtube/repository/YouTubeMusicPlaybackRepository.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/playback/YouTubePlayableAudioSelection.kt",
            "modules/data/youtube/src/main/java/moe/ouom/neriplayer/data/youtube/cache/YouTubePlayableAudioCache.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/bootstrap/YouTubePlaybackBootstrapOwner.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/playback/YouTubePlaybackStreamAccessOwner.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/potoken/YouTubePlaybackManifestPoToken.kt",
            "modules/data/youtube/src/main/java/moe/ouom/neriplayer/data/youtube/repository/YouTubePlaybackDependencies.kt",
            "modules/api/youtube/src/main/java/moe/ouom/neriplayer/api/youtube/transport/YouTubePlaybackHttpPolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerPersistenceExtensions.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerQueueCommandExtensions.kt",
            "modules/core/playback-queue/src/main/java/moe/ouom/neriplayer/core/player/queue/policy/PlayerQueueEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsEditor.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionController.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionOpenGate.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionResources.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionReusePolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionStateProjection.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSelectedDeviceKeyPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppPlaybackVisualOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/theme/reveal/AppThemeRevealCapture.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/dialog/AppGlobalDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/banner/AppStatusBanners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/migration/SettingsDownloadDirectoryMigrationSnapshot.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/migration/SettingsDownloadDirectoryMigrationRecovery.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryApplyOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryPreparationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectorySelectionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryResetOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryGuardOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryPendingOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectorySwitchOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryLocalState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryStateSync.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/navigation/SettingsNavigationState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/playback/SettingsQualityPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/about/SettingsAboutInteractions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/backup/SettingsBackupTransferController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/auth/SettingsAccountAuthController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/auth/SettingsAccountStatusContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsBackgroundAppearanceController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/storage/SettingsStoragePageController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/home/SettingsHomeStartPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/SettingsScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditLyricsSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditRestoreSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSave.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSearchSheet.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/media/LocalPlaybackMediaResolver.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/media/PlaybackMediaItemFactory.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackConfirmationOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackSnapshotSource.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsFastStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsBackgroundStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsResolution.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/link/ListenTogetherControllerLinkOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/ltw/PlayerManagerListenTogetherHost.kt",
            "modules/core/player-runtime/src/main/java/moe/ouom/neriplayer/core/player/runtime/stats/PlaybackStatsOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackStatsWritePort.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/state/ListenTogetherRoomStateOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/state/ListenTogetherSessionProjection.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/control/ListenTogetherPendingEvents.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerPlaybackExtensions.kt",
            "modules/core/playback-queue/src/main/java/moe/ouom/neriplayer/core/player/queue/policy/PlayerQueueNavigationOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerQueueNavigationExtensions.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbExclusiveLivenessOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbExclusiveLivenessPort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbInterruptedPlaybackOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbInterruptedPlaybackPort.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/control/ListenTogetherLocalControlOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NeriApp.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRoute.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteOwners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsHostBindings.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppMainTabRouteSelection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/debug/AppDebugCrashActionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppLyricOffsetSettingsOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppSettingsCacheClearOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationGraph.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationScaffold.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/banner/AppManagedProcessingBannerOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/theme/reveal/AppThemeRevealOverlayHost.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/dialog/AppGlobalDialogHosts.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationSceneRenderer.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppStartupDestinationEffect.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppNowPlayingOverlay.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppNowPlayingBackdrop.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurImageRequests.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBackdropLayers.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurEffectOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/connection/ListenTogetherSocketHealthOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/liveness/ListenTogetherHeartbeatOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/liveness/ListenTogetherListenerWatchdogOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppUsbExclusiveSettingsActions.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/connection/ListenTogetherConnectionRecoveryOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/connection/ListenTogetherConnectionRecoveryPolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/lifecycle/PlayerManagerLifecycleExtensions.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbRouteTransitionOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSinkRouteOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSinkRoutePolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbSinkRoutePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbRoutePlayerSnapshot.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSystemAudioRouteOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSystemAudioRoutePolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbSystemAudioRoutePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackRouteOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackRoutePolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackNativeRoutePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbPlaybackRoutePort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/route/AudioDeviceRouteOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/route/AudioDeviceRoutePolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/route/PlayerManagerAudioDeviceRoutePort.kt",
            "modules/core/player-policy/src/main/java/moe/ouom/neriplayer/core/player/policy/command/LocalRoomControlRestriction.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/ListenTogetherSessionManager.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/socket/ListenTogetherRoomSocketEventOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/control/ListenTogetherSocketControlResultOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/membership/ListenTogetherRoomMembershipOwner.kt",
            "modules/data/ltw/src/main/java/moe/ouom/neriplayer/data/ltw/session/membership/ListenTogetherMembershipTransport.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/PlayerManager.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlaybackSoundOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackSoundPort.kt",
            "modules/core/player-runtime/src/main/java/moe/ouom/neriplayer/core/player/runtime/quality/PlaybackQualityOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackQualityPort.kt",
            "modules/core/player-runtime/src/main/java/moe/ouom/neriplayer/core/player/runtime/transport/PlaybackTransportOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackTransportPort.kt",
            "modules/core/player-runtime/src/main/java/moe/ouom/neriplayer/core/player/runtime/progress/PlaybackProgressOwner.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerPlaybackProgressPort.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackAutoSkipPolicy.kt",
            "modules/feature/player/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/PlayerManagerUsbLoudPlaybackSnapshotPort.kt"
        ).forEach { path ->
            val file = File(projectRoot, path)
            assertTrue("缺少受保护源码：$path", file.isFile)
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "$path 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }

        val nativeSources = File(projectRoot, "app/src/main/cpp/usb/exclusive")
        assertTrue("缺少 USB 独占输出源码目录", nativeSources.isDirectory)
        val nativeFiles = nativeSources.listFiles().orEmpty()
            .filter { it.isFile && it.extension in setOf("cpp", "h") }
        assertTrue("USB 独占输出源码目录为空", nativeFiles.isNotEmpty())
        nativeFiles.forEach { file ->
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "${file.relativeTo(projectRoot)} 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }
    }
}
