package moe.ouom.neriplayer.architecture

import java.io.File
import org.junit.Assert.assertTrue
import org.junit.Test

class OwnedMainSourceLineBudgetTest {
    @Test
    fun `completed owned source sections stay below 2000 physical lines`() {
        val projectRoot = LocalManagementLineBudget.findProjectRoot(
            File(System.getProperty("user.dir") ?: ".")
        )
        listOf(
            "app/src/main/java/moe/ouom/neriplayer/data/settings/AutoSettingsSchema.kt",
            "app/src/main/java/moe/ouom/neriplayer/data/settings/PlaybackSettingsSection.kt",
            "data/bilibili/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliClient.kt",
            "data/bilibili/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliCommentApi.kt",
            "data/bilibili/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliCookieSession.kt",
            "data/bilibili/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliRequestSupport.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/home/HomeScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/home/HomeContinueSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryPreflight.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/navigation/SettingsNavigationSearch.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsThemeControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingQueueSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricSettingsSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingSharedComponents.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupBackupRestoreStep.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreSearchResultRows.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreBrowseContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/explore/ExploreGlassPillSurface.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/MainTabNavigationMotion.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/playback/SettingsPlaybackControlLayout.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsPersonalizationContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/listentogether/SettingsListenTogetherSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingPlaybackControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingSecondaryActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkPolicies.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackCoverSourceResolver.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackNotificationWidgetPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServiceMetadataPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/UsbExclusiveServiceKeepAliveOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidUsbExclusiveKeepAlivePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/UsbExclusiveMediaSessionVolumeRouter.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidUsbExclusiveVolumeRoutingPort.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeStreamingCipherResolution.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayerRequestComposer.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AudioPlayerService.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServicePresentationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServicePresentationSource.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidPlaybackServicePresentationPort.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayerResponseParsers.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveAudioSink.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusivePcmWriter.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveSinkVolumeOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/AndroidUsbExclusiveSinkVolumePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveTransportStartPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCover.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverTopBar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingTrackIdentity.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverActionToolbar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverControlsPlacement.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/cover/NowPlayingCoverLyrics.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicClient.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicProtocolModels.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicResponseParser.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicPlaybackRepository.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayableAudioSelection.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayableAudioCache.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackBootstrapOwner.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackStreamAccessOwner.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackManifestPoToken.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackDependencies.kt",
            "data/youtube/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackHttpPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerPersistenceExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerQueueCommandExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerQueueEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsEditor.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionController.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionOpenGate.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionResources.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionReusePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionStateProjection.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSelectedDeviceKeyPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppPlaybackVisualOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/theme/reveal/AppThemeRevealCapture.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/dialog/AppGlobalDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/banner/AppStatusBanners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/migration/SettingsDownloadDirectoryMigrationSnapshot.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/migration/SettingsDownloadDirectoryMigrationRecovery.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryApplyOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryPreparationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectorySelectionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryResetOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryGuardOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/operation/SettingsDownloadDirectoryPendingOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectorySwitchOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryLocalState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryStateSync.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/download/directory/SettingsDownloadDirectoryActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/navigation/SettingsNavigationState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/playback/SettingsQualityPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/about/SettingsAboutInteractions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/backup/SettingsBackupTransferController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/auth/SettingsAccountAuthController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/auth/SettingsAccountStatusContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/appearance/SettingsBackgroundAppearanceController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/storage/SettingsStoragePageController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/home/SettingsHomeStartPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/settings/SettingsScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditLyricsSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditRestoreSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSave.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/edit/NowPlayingSongEditSearchSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/media/LocalPlaybackMediaResolver.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/media/PlaybackMediaItemFactory.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackConfirmationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackSnapshotSource.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/NowPlayingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsLoadSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsFastStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsBackgroundStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/nowplaying/lyrics/NowPlayingLyricsResolution.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherControllerLinkOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/PlayerManagerListenTogetherLinkPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackStatsOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackStatsWritePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherRoomStateOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherSessionProjection.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherPendingEvents.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerPlaybackExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerQueueNavigationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerQueueNavigationExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbExclusiveLivenessOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbExclusiveLivenessPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbInterruptedPlaybackOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbInterruptedPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherLocalControlOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NeriApp.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRoute.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteOwners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsHostBindings.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppMainTabRouteSelection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/debug/AppDebugCrashActionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/route/AppSettingsRouteState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppLyricOffsetSettingsOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppSettingsCacheClearOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationGraph.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationScaffold.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/banner/AppManagedProcessingBannerOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/theme/reveal/AppThemeRevealOverlayHost.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/dialog/AppGlobalDialogHosts.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppNavigationSceneRenderer.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/navigation/AppStartupDestinationEffect.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppNowPlayingOverlay.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/AppNowPlayingBackdrop.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurImageRequests.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBackdropLayers.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/playback/visual/NowPlayingBlurEffectOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherSocketHealthOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherHeartbeatOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherListenerWatchdogOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/settings/owner/AppUsbExclusiveSettingsActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherConnectionRecoveryOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherConnectionRecoveryPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/lifecycle/PlayerManagerLifecycleExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbRouteTransitionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSinkRouteOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSinkRoutePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbSinkRoutePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbRoutePlayerSnapshot.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSystemAudioRouteOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbSystemAudioRoutePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbSystemAudioRoutePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackRouteOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackRoutePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/UsbPlaybackNativeRoutePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/route/PlayerManagerUsbPlaybackRoutePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/route/AudioDeviceRouteOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/route/AudioDeviceRoutePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/route/PlayerManagerAudioDeviceRoutePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/policy/command/LocalRoomControlRestriction.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/ListenTogetherSessionManager.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherRoomSocketEventOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherSocketControlResultOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherRoomMembershipOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherMembershipTransport.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/PlayerManager.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlaybackSoundOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackSoundPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlaybackQualityOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackQualityPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlaybackTransportOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/audio/output/PlayerManagerPlaybackTransportPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackProgressOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerPlaybackProgressPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackAutoSkipPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/PlayerManagerUsbLoudPlaybackSnapshotPort.kt"
        ).forEach { path ->
            val file = File(projectRoot, path)
            assertTrue("缺少受保护源码：$path", file.isFile)
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "$path 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }

        val nativeSources = File(projectRoot, "app/src/main/cpp/usb/exclusive")
        assertTrue("缺少 USB 独占输出源码目录", nativeSources.isDirectory)
        val nativeFiles = nativeSources.listFiles().orEmpty()
            .filter { it.isFile && it.extension in setOf("cpp", "h") }
        assertTrue("USB 独占输出源码目录为空", nativeFiles.isNotEmpty())
        nativeFiles.forEach { file ->
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "${file.relativeTo(projectRoot)} 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }
    }
}
