package moe.ouom.neriplayer.architecture

import java.io.File
import org.junit.Assert.assertTrue
import org.junit.Test

class OwnedMainSourceLineBudgetTest {
    @Test
    fun `completed owned source sections stay below 2000 physical lines`() {
        val projectRoot = LocalManagementLineBudget.findProjectRoot(
            File(System.getProperty("user.dir") ?: ".")
        )
        listOf(
            "app/src/main/java/moe/ouom/neriplayer/data/settings/AutoSettingsSchema.kt",
            "app/src/main/java/moe/ouom/neriplayer/data/settings/PlaybackSettingsSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliClient.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliCommentApi.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliCookieSession.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/bili/BiliRequestSupport.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/HomeScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/HomeContinueSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryPreflight.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsNavigationSearch.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsThemeControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingQueueSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricSettingsSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupOnboardingSharedComponents.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/onboarding/StartupBackupRestoreStep.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/ExploreScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/ExploreSearchResultRows.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/ExploreBrowseContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/ExploreGlassPillSurface.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/MainTabNavigationMotion.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsPlaybackControlLayout.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsPersonalizationContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsListenTogetherController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsListenTogetherDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsListenTogetherSection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingPlaybackControls.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSecondaryActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkPolicies.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackArtworkSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackCoverSourceResolver.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackNotificationWidgetPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServiceMetadataPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/UsbExclusiveServiceKeepAliveOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidUsbExclusiveKeepAlivePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/UsbExclusiveMediaSessionVolumeRouter.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidUsbExclusiveVolumeRoutingPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeStreamingCipherResolution.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayerRequestComposer.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AudioPlayerService.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServicePresentationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/PlaybackServicePresentationSource.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/service/AndroidPlaybackServicePresentationPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayerResponseParsers.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveAudioSink.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusivePcmWriter.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveSinkVolumeOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/sink/UsbExclusiveTransportStartPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingCover.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingCoverTopBar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingTrackIdentity.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingCoverActionToolbar.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingCoverControlsPlacement.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingCoverLyrics.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicClient.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicProtocolModels.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicResponseParser.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubeMusicPlaybackRepository.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayableAudioSelection.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlayableAudioCache.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackBootstrapOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackStreamAccessOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackManifestPoToken.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackDependencies.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/api/youtube/YouTubePlaybackHttpPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerPersistenceExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerManagerQueueCommandExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/persistence/PlayerQueueEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsEditor.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionController.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionOpenGate.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionResources.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionReusePolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSessionStateProjection.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/session/UsbExclusiveSelectedDeviceKeyPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppPlaybackVisualOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppThemeRevealCapture.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppGlobalDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppStatusBanners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryMigrationSnapshot.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryMigrationRecovery.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryApplyOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryPreparationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectorySelectionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryResetOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryGuardOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryPendingOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectorySwitchOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryLocalState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryStateSync.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsDownloadDirectoryActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsNavigationState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsQualityPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsAboutInteractions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsBackupTransferController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsAccountAuthController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsAccountStatusContent.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsBackgroundAppearanceController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsStoragePageController.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsHomeStartPresentation.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/tab/SettingsScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditDialogs.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditLyricsSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditRestoreSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditSave.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingSongEditSearchSheet.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/media/LocalPlaybackMediaResolver.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/media/PlaybackMediaItemFactory.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackConfirmationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/confirmation/UsbExclusiveLoudPlaybackSnapshotSource.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingScreen.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsLoadPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsLoadOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsLoadSources.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsFastStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsBackgroundStage.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/screen/NowPlayingLyricsResolution.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherControllerLinkOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/PlayerManagerListenTogetherLinkPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackStatsOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlaybackStatsWritePort.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherRoomStateOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherSessionProjection.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherPendingEvents.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerPlaybackExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerQueueNavigationOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/playback/PlayerManagerQueueNavigationExtensions.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbExclusiveLivenessOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbExclusiveLivenessPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/UsbInterruptedPlaybackOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/core/player/usb/recovery/PlayerManagerUsbInterruptedPlaybackPort.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherLocalControlOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NeriApp.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsRoute.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsRouteOwners.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsRouteActions.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsHostBindings.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppMainTabRouteSelection.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppDebugCrashActionOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsRouteState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppLyricOffsetSettingsOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppSettingsCacheClearOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppNavigationGraph.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppNavigationScaffold.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppManagedProcessingBannerOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppThemeRevealOverlayHost.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppGlobalDialogHosts.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppNavigationSceneRenderer.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppStartupDestinationEffect.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppNowPlayingOverlay.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/AppNowPlayingBackdrop.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NowPlayingBlurPolicy.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NowPlayingBlurState.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NowPlayingBlurImageRequests.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NowPlayingBackdropLayers.kt",
            "app/src/main/java/moe/ouom/neriplayer/ui/NowPlayingBlurEffectOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherSocketHealthOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherHeartbeatOwner.kt",
            "app/src/main/java/moe/ouom/neriplayer/listentogether/session/ListenTogetherListenerWatchdogOwner.kt"
        ).forEach { path ->
            val file = File(projectRoot, path)
            assertTrue("缺少受保护源码：$path", file.isFile)
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "$path 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }

        val nativeSources = File(projectRoot, "app/src/main/cpp/usb/exclusive")
        assertTrue("缺少 USB 独占输出源码目录", nativeSources.isDirectory)
        val nativeFiles = nativeSources.listFiles().orEmpty()
            .filter { it.isFile && it.extension in setOf("cpp", "h") }
        assertTrue("USB 独占输出源码目录为空", nativeFiles.isNotEmpty())
        nativeFiles.forEach { file ->
            val physicalLines = LocalManagementLineBudget.countPhysicalLines(file)
            assertTrue(
                "${file.relativeTo(projectRoot)} 有 $physicalLines 行，必须少于 ${LocalManagementLineBudget.MAX_EXCLUSIVE} 行",
                LocalManagementLineBudget.isWithinBudget(physicalLines)
            )
        }
    }
}
